"""empty message

Revision ID: 0b020e0e3740
Revises: 
Create Date: 2018-08-01 11:45:41.761899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b020e0e3740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Integer(), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=60), nullable=True),
    sa.Column('image_description', sa.String(length=200), nullable=True),
    sa.Column('image_filename', sa.String(length=250), nullable=True),
    sa.Column('image_frame_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_name')
    )
    op.create_table('segmentedimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segmented_image_jpg_name', sa.String(length=200), nullable=True),
    sa.Column('segmented_image_dicom_name', sa.String(length=200), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('segmented_image_date', sa.DateTime(), nullable=False),
    sa.Column('segmented_image_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segmentedpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segmented_point_name', sa.String(length=200), nullable=True),
    sa.Column('segmented_point_data', sa.String(length=250), nullable=True),
    sa.Column('segmented_image_id', sa.Integer(), nullable=False),
    sa.Column('segmented_point_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['segmented_image_id'], ['segmentedimages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segmented_point_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segmentedpoints')
    op.drop_table('segmentedimages')
    op.drop_table('images')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
